# Default values for spark-addon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

workerServiceAccount: airflow-worker

annotations: {}

labels : {}
