apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-addon.name" . }}-role-binding
  labels:
    {{- include "spark-addon.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.workerServiceAccount }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "spark-addon.name" . }}-driver-role
  apiGroup: rbac.authorization.k8s.io
